apiVersion: v1
kind: Secret
metadata:
  name: vapp-db-secret
  namespace: vapp-lease
type: Opaque
data:
  POSTGRES_USER: <USER>
  POSTGRES_PASSWORD: <PASSWORD>
  POSTGRES_DB: <DB_NAME>
  POSTGRES_HOST: <DB_HOST>
